alter table public.artifacts
  add column if not exists project text not null default 'unassigned',
  add column if not exists intended_use text not null default 'unassigned',
  add column if not exists notes text not null default '';

create index if not exists artifacts_project_idx on public.artifacts (project);
create index if not exists artifacts_intended_use_idx on public.artifacts (intended_use);

alter table public.artifacts drop constraint if exists artifacts_visibility_check;
alter table public.artifacts add constraint artifacts_visibility_check
  check (visibility in ('private','internal','employee','team','public','exportable'));

insert into public.tags (name, slug, tag_type, description)
values
  ('image','medium-image','medium','Controlled medium value.'),
  ('pdf','medium-pdf','medium','Controlled medium value.'),
  ('text','medium-text','medium','Controlled medium value.'),
  ('markdown','medium-markdown','medium','Controlled medium value.'),
  ('doc','medium-doc','medium','Controlled medium value.'),
  ('lore','medium-lore','medium','Controlled medium value.'),
  ('rules','medium-rules','medium','Controlled medium value.'),
  ('reference','medium-reference','medium','Controlled medium value.'),
  ('export','medium-export','medium','Controlled medium value.'),
  ('other','medium-other','medium','Controlled medium value.'),
  ('creative-systems','project-creative-systems','project','Controlled project value.'),
  ('para-poker','project-para-poker','project','Controlled project value.'),
  ('para-profiles','project-para-profiles','project','Controlled project value.'),
  ('gauntlet','project-gauntlet','project','Controlled project value.'),
  ('time-twister','project-time-twister','project','Controlled project value.'),
  ('merch','project-merch','project','Controlled project value.'),
  ('lore-pages','project-lore-pages','project','Controlled project value.'),
  ('achievement-cards','project-achievement-cards','project','Controlled project value.'),
  ('unassigned','project-unassigned','project','Controlled project value.'),
  ('lore-page','function-lore-page','function','Controlled intended-use value.'),
  ('profile-art','function-profile-art','function','Controlled intended-use value.'),
  ('profile-background','function-profile-background','function','Controlled intended-use value.'),
  ('card-art','function-card-art','function','Controlled intended-use value.'),
  ('achievement','function-achievement','function','Controlled intended-use value.'),
  ('badge','function-badge','function','Controlled intended-use value.'),
  ('sigil','function-sigil','function','Controlled intended-use value.'),
  ('merch-design','function-merch-design','function','Controlled intended-use value.'),
  ('rules-reference','function-rules-reference','function','Controlled intended-use value.'),
  ('game-data','function-game-data','function','Controlled intended-use value.'),
  ('admin-doc','function-admin-doc','function','Controlled intended-use value.'),
  ('marketing','function-marketing','function','Controlled intended-use value.'),
  ('reference-only','function-reference-only','function','Controlled intended-use value.'),
  ('unassigned','function-unassigned','function','Controlled intended-use value.'),
  ('internal-only','rights-internal-only','rights','Controlled rights value.'),
  ('public-safe','rights-public-safe','rights','Controlled rights value.'),
  ('unknown','rights-unknown','rights','Controlled rights value.'),
  ('original','rights-original','rights','Controlled rights value.'),
  ('ai-generated','rights-ai-generated','rights','Controlled rights value.'),
  ('third-party-reference','rights-third-party-reference','rights','Controlled rights value.'),
  ('needs-review','rights-needs-review','rights','Controlled rights value.'),
  ('needs-tagging','review-needs-tagging','review','Controlled review value.'),
  ('needs-categorization','review-needs-categorization','review','Controlled review value.'),
  ('needs-rights','review-needs-rights','review','Controlled review value.'),
  ('needs-review','review-needs-review','review','Controlled review value.'),
  ('approved','review-approved','review','Controlled review value.'),
  ('rejected','review-rejected','review','Controlled review value.'),
  ('approved','canon-approved','canon','Controlled canon value.'),
  ('draft','canon-draft','canon','Controlled canon value.'),
  ('working','canon-working','canon','Controlled canon value.'),
  ('deprecated','canon-deprecated','canon','Controlled canon value.'),
  ('conflict','canon-conflict','canon','Controlled canon value.'),
  ('non-canon','canon-non-canon','canon','Controlled canon value.'),
  ('reference-only','canon-reference-only','canon','Controlled canon value.'),
  ('private','visibility-private','visibility','Controlled visibility value.'),
  ('internal','visibility-internal','visibility','Controlled visibility value.'),
  ('team','visibility-team','visibility','Controlled visibility value.'),
  ('public','visibility-public','visibility','Controlled visibility value.'),
  ('exportable','visibility-exportable','visibility','Controlled visibility value.'),
  ('uploaded','workflow-uploaded','workflow','Controlled workflow value.'),
  ('imported','workflow-imported','workflow','Controlled workflow value.'),
  ('needs-metadata','workflow-needs-metadata','workflow','Controlled workflow value.'),
  ('categorized','workflow-categorized','workflow','Controlled workflow value.'),
  ('reviewed','workflow-reviewed','workflow','Controlled workflow value.'),
  ('export-ready','workflow-export-ready','workflow','Controlled workflow value.'),
  ('archived','workflow-archived','workflow','Controlled workflow value.'),
  ('favorite','freeform-favorite','freeform','Starter freeform tag.'),
  ('possible-drop','freeform-possible-drop','freeform','Starter freeform tag.'),
  ('needs-case','freeform-needs-case','freeform','Starter freeform tag.'),
  ('strong-direction','freeform-strong-direction','freeform','Starter freeform tag.'),
  ('weird','freeform-weird','freeform','Starter freeform tag.'),
  ('revisit','freeform-revisit','freeform','Starter freeform tag.')
on conflict (slug) do update
set name = excluded.name,
    tag_type = excluded.tag_type,
    description = excluded.description;
